# Generated by Django 4.2.2 on 2023-06-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
